# 服务配置
server:
  host: 'localhost'
  port: 3000
  prefix: '/api'
# JWTModule相关配置
jwt:
  secret: ''
  expireIn: '7d' #表示过期时间7天
# sequelize相关
mysql:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'baicai666666'
  database: 'admin_api'
  dialect: 'mysql'
  synchronize: true
  autoLoadModels: true
  # 打印数据库日志（sequelize）
  logging: true
  # 连接池配置
  poolSize: 20
redis:
  enable: false #true/false 表示是否启用redis
  host: 'localhost'
  port: 6379
  enableAuth: false
  db: 0
logger:
  level: 'debug'
swagger:
  enable: true
